server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index Index.html;

    # Отдаём статику напрямую
    location / {
        try_files $uri $uri/ /Index.html;
    }

    # Опционально: gzip-сжатие
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
